# -*- coding: utf-8 -*-
import threading

# Form implementation generated from reading ui file 'untitled_people.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QFont


class Ui_ThirdWindow(object):

    def setupUi(self, ThirdWindow):
        ThirdWindow.setObjectName("ThirdWindow")
        ThirdWindow.setFixedSize(570, 637)
        font = QtGui.QFont()
        font.setPointSize(37)
        ThirdWindow.setFont(font)
        ThirdWindow.setStyleSheet("QWidget {\n"
                                  "    background-color: rgb(95, 95, 95);\n"
                                  "    color: rgb(250, 250, 250);\n"
                                  "}\n"
                                  "")
        self.centralwidget = QtWidgets.QWidget(ThirdWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setEnabled(False)
        self.sendButton.setGeometry(QtCore.QRect(310, 270, 93, 28))
        self.sendButton.setIconSize(QtCore.QSize(16, 16))
        self.sendButton.setAutoRepeatInterval(100)
        self.sendButton.setObjectName("sendButton")
        # self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        # self.tableWidget.setGeometry(QtCore.QRect(20, 310, 391, 291))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        # sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        # self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.messages = QtWidgets.QTextBrowser(self.centralwidget)
        self.messages.setGeometry(QtCore.QRect(10, 360, 550, 461))
        self.messages.setFont(QFont("Lucida Console", 30))
        self.messages.setAlignment(Qt.AlignHCenter | Qt.AlignVCenter)
        self.messages.setObjectName("messages")
        self.number = QtWidgets.QLineEdit(self.centralwidget)
        self.number.setEnabled(False)
        self.number.setGeometry(QtCore.QRect(170, 270, 121, 31))
        self.number.setObjectName("number")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 521, 61))
        font = QtGui.QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.guess_number = QtWidgets.QLineEdit(self.centralwidget)
        self.guess_number.setEchoMode(QtWidgets.QLineEdit.Password)
        self.guess_number.setGeometry(QtCore.QRect(30, 100, 171, 31))
        self.guess_number.setObjectName("guess_number")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(250, 100, 131, 31))
        ThirdWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ThirdWindow)
        self.statusbar.setObjectName("statusbar")
        ThirdWindow.setStatusBar(self.statusbar)
        self.retranslateUi(ThirdWindow)
        QtCore.QMetaObject.connectSlotsByName(ThirdWindow)

    def retranslateUi(self, ThirdWindow):
        _translate = QtCore.QCoreApplication.translate
        ThirdWindow.setWindowTitle(_translate("ThirdWindow", "MainWindow"))
        self.sendButton.setText(_translate("ThirdWindow", "Send"))
        self.number.setText(_translate("ThirdWindow", "1234"))
        self.label_3.setText(_translate("ThirdWindow", "Write your number"))
        self.label.setText(_translate("ThirdWindow", "Make a number to the enemy"))
        self.send_button.setText(_translate("ThirdWindow", "Send"))

