# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(638, 763)
        Form.setStyleSheet("QWidget {\n"
"    background-color:rgb(95, 95, 95);\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setEnabled(True)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 611, 301))
        self.textEdit.setStyleSheet("")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 330, 551, 401))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Desktop/Снимок экрана (160).png"))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:1; text-indent:0px; line-height:138%; background-color:transparent;\"><a name=\"docs-internal-guid-c56cd276-7fff-64dd-7e0c-727d98c8d870\"></a><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">П</span><span style=\" font-family:\'Courier New\'; font-size:12pt; color:#000000;\">ервый игрок задумывает четырехзначное число, так чтобы все цифры числа были разные. Цель второго игрока — отгадать это число. Каждый ход, отгадывающий вводит число, тоже четырехзначное и с разными цифрами. Если цифра из названного числа есть в отгадываемом числе, то эта ситуация называется корова. Если цифра из названного числа есть в отгадываемом числе и стоит в том же месте, то эта ситуация называется бык.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\">Например, первый игрок задумал 6109, а второй игрок назвал 0123. То первый игрок должен сказать: один бык и одна корова (1б,1к).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"><br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; color:#000000; background-color:transparent;\">Свое слово задумывает каждый партнер. Ходят по очереди. Выигрывает тот, кто раньше отгадает число соперника.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\"><br /></span></p></body></html>"))
